version: '3'

services:

  node:
    build: ./
    restart: always
    ports:
      - 3030:3030
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: "npm start"
    labels:
      - "traefik.frontend.rule=Host:testing.gif"
